### ISSUE TITLE
Release for 0.2

### ISSUE THREAD

**Issue by h3xstream** [pedro-walter/django-login-required#1]
```
>pip install django-login-required

Installing collected packages: django-login-required
Successfully installed django-login-required-0.1
```
Are you planning to release the version 0.2?

https://pypi.org/project/django-login-required/#history

**Comment by pedro-walter** [comment]
When I tried uploading it to pip, I had tons of trouble. I need to try it again. In the meantime, you can use it pointing to the latest commit, which is essentially v0.2.

[This stackoverflow answer shows how](https://stackoverflow.com/a/13754517/2232455)

Will take a look at it tomorrow.

**Comment by pedro-walter** [comment]
Uploaded v0.2 to PyPi
